version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_auth_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel_auth_network
    depends_on:
      - db
      - redis
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel_auth
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_password
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

  nginx:
    image: nginx:alpine
    container_name: laravel_auth_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_auth_network

  db:
    image: mysql:8.0
    container_name: laravel_auth_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_auth
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_auth_network
    ports:
      - "3307:3306"

  redis:
    image: redis:alpine
    container_name: laravel_auth_redis
    restart: unless-stopped
    networks:
      - laravel_auth_network
    ports:
      - "6380:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_auth_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_password
    networks:
      - laravel_auth_network
    ports:
      - "8081:80"
    depends_on:
      - db

networks:
  laravel_auth_network:
    driver: bridge

volumes:
  db_data:
    driver: local
